[package]
name = "minesweeper-nannou-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minesweeper-logic = { path = "../minesweeper-logic" }
nannou = "0.18.0"
