name: "Build + Test (Logic Only)"

on:
  push:
    branches: [ main ]
    paths:
      - minesweeper-logic/**
  pull_request:
    branches: [ main ]
    paths:
      - minesweeper-logic/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: ./minesweeper-logic
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./minesweeper-logic
      run: cargo test --verbose
